### PR TITLE
Add new StreamPlayer.getDuration() API

### LINKED ISSUE #61: Add getDurationInMilliseconds() to StreamPlayer API
My application is meant to play audio files which are sometimes shorter than 1 second (eg. Drum sounds for music production). For this case, it'd be useful to have a `getDurationInMilliseconds()` function in the `StreamPlayer` class.

I saw that the `getDurationInSeconds()`[ implementation for `FileDataSource`](https://github.com/goxr3plus/java-stream-player/blob/fd27f0b3a5e026fce70aaab4c1894ecdc9363eb7/src/main/java/com/goxr3plus/streamplayer/stream/FileDataSource.java#L32) calls `TimeTool.durationInSeconds()`  which is implemented with [`TimeTool.durationInMilliseconds(name, type)`](https://github.com/goxr3plus/java-stream-player/blob/9a0617f038d91fca2e4502ef49d09883477debc1/src/main/java/com/goxr3plus/streamplayer/tools/TimeTool.java#L104). This gives me hope that this wouldn't be too hard to add to the StreamPlayer API. 

I'd like to submit a PR for this, however I wanted to bring up the topic before I get to work on it.

Any thoughts?

### PR DESCRIPTION
**Pull request by AObuchow**
Allow duration to be retrieved in milliseconds, and as a Duration
object.

Fix #61

Signed-off-by: Andrew Obuchowicz <andrewobuchowicz@gmail.com>

# Description

Please include a summary of the change and which issue is fixed.
List any dependencies that are required for this change.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] This change requires a documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

# Has This Been Tested?

- [x] Yes, test cases included
- [ ] No

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AObuchow** [comment]
@HelgeStenstrom if you have any improvement suggestions, let me know. Will give you a chance to check it out before I merge.

**Comment by AObuchow** [comment]
Actually.. I just tested this out on a short .wav file and it still gives a duration of 0. This needs more work before it can be merged.

**Comment by AObuchow** [comment]
### Some additional info
- I used the algorithm from the top voted answer [here](https://stackoverflow.com/questions/6220660/calculating-the-length-of-mp3-frames-in-milliseconds) to calculate the length of a .mp3 when its duration is less than 1 second.
- The samples per frame for each MPEG layer was referenced from [here](https://wiki.hydrogenaud.io/index.php?title=MP3&action=view&section=4#Decoding_of_MP3_audio)
- The output of getDurationInMilliseconds() differs from `.wav`/ `.ogg` when compared to `.mp3`
    - This seems to be true for other applications, eg. `sox`, see below output for reference.
```
[aobuchow@localhost java-stream-player]$ sox kick.mp3 -n stat
Samples read:              6880
Length (seconds):      0.156009 <-------------------- 
Scaled by:         2147483647.0
Maximum amplitude:     0.855614
Minimum amplitude:    -1.000000
Midline amplitude:    -0.072193
Mean    norm:          0.317808
Mean    amplitude:    -0.000301
RMS     amplitude:     0.441869
Maximum delta:         0.408761
Minimum delta:         0.000000
Mean    delta:         0.005034
RMS     delta:         0.013910
Rough   frequency:          220
Volume adjustment:        1.000

Can't guess the type

[aobuchow@localhost java-stream-player]$ sox kick.wav -n stat
Samples read:              4688
Length (seconds):      0.106304 <-------------------- 
Scaled by:         2147483647.0
Maximum amplitude:     0.854838
Minimum amplitude:    -0.977237
Midline amplitude:    -0.061199
Mean    norm:          0.461796
Mean    amplitude:    -0.000225
RMS     amplitude:     0.534399
Maximum delta:         0.405442
Minimum delta:         0.000000
Mean    delta:         0.006001
RMS     delta:         0.016087
Rough   frequency:          211
Volume adjustment:        1.023

Try: -t raw -e mu-law -b 8 
```

**Comment by AObuchow** [comment]
@HelgeStenstrom it should be good for a review now, if you desire to do so.

**Comment by goxr3plus** [comment]
I think it's good enough. @HelgeStenstrom let me know if i am missing something i merge for now.

**Comment by goxr3plus** [comment]
Great Job :)

**Comment by AObuchow** [comment]
Thanks @goxr3plus ! :)

**Pull request merged**
