### PR TITLE
Extract class from stream player

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
This is just a draft. It should not be merged.

I'm playing with the idea of splitting StreamPlayer into smaller classes. As a first try, I have created a new class Outlet (maybe a bad name, but it can be changed). The SourceDataStream and the associated controls (gain, pan etc) have been moved to the new class.
A few methods have been moved to the new class. More will follow. The methods that I'm moving are the ones that primarily work on the fields that have already been moved.

I have also made an interface with the public methods of StreamPlayer. The intention is to have a safety net, so that I don't change the de-facto interface (as seen by the application) by mistake.
But the separation can be better, if the interface can be changed, so that the application cannot call streamPlayer.getGain(), but has to call outlet.getGain() for the same purpose. If that is allowed, the wrapper methods in StreamPlayer that now calls methods in Outlet can be removed.

Again: this is experimental. 
The application works as usual. Unit tests test were written before the refactoring, and work after it too.

See also: https://refactoring.com/catalog/extractClass.html

### CODE REVIEW

**Comment by goxr3plus** [comment]
I had exactly the same idea today in the morning, continue, i am watching the changes now. We want to maintain backward compatibility with the applications already using StreamPLayer if that is possible.

**Comment by HelgeStenstrom** [comment]
I will not do intermediate pull request, but you can watch my branch.

**Comment by goxr3plus** [comment]
By the way passing XR3Player to Java 13 in September, and this project in Java 11, we can use multirelease so users can both use it with Java 8 and Java11 and above, i haven't done it before but how hard it can be %)

**Comment by HelgeStenstrom** [comment]
I think this is ready to be merged now. There are a number of issues that I would like to deal with, but that is best done after this code is merged.

There are a lot of changes. I have done testing, and I haven't done any deliberate behavior changes, just refactorings that shouldn't change any behavior. But mistakes happen.
Tests are done mainly using the test class SourceDataLineTest.

The new class is called Outlet, and that is maybe not a good name. But it's easy to change later.

The StreamPlayer has the same de facto interface. I have also made an interface (in the Java sense), called StreamPlayerInterface, that StreamPlayer implements. The interface name is bad, I would rather call the interface SteamPlayer, but I didn't want to change the name of the implementation class at this time, as implementations would have to change how they create a new instance of the player.

**Comment by HelgeStenstrom** [comment]
There are a lot of commits. They should probably be squashed.

**Comment by goxr3plus** [comment]
We will change the names before the next release and show a tutorial on the read me for new users :)

**Comment by goxr3plus** [comment]
I read most of it, merging, we need to go through good testing.

**Pull request merged**
