### PR TITLE
Resolved #3, #6, #8

### LINKED ISSUE #3: Likely cause of split packages
https://github.com/goxr3plus/java-stream-player/blob/2f7d16dcf689a5335e91fe91bd6bfbdfe173cd6e/pom.xml#L100-L109

I think these two dependencies creates split packages, which in turn causes a runtime problem:

```text
Error:java: the unnamed module reads package org.tritonus.share.sampled.mixer from both tritonus.share and tritonus.all
```
in a program using Java 11 that has this repo as dependency.

Compare with this discussion: 
https://stackoverflow.com/questions/42358084/package-conflicts-with-automatic-modules-in-java-9

### PR DESCRIPTION
**Pull request by TonalidadeHidrica**
All problems mentioned in those issues have been resolved, I think.
Please remove this branch and [issue-3](/goxr3plus/java-stream-player/tree/issue-3) after merging.

### CODE REVIEW

**Comment by TonalidadeHidrica** [comment]
No link to the issue when I mentioned issue indexes in the title?  Well then, again, only for linking, this pull request resolves #3 , #6 and #8 .

**Comment by goxr3plus** [comment]
Will the library work with JDK < 8 after this pull request?

**Comment by TonalidadeHidrica** [comment]
Unfortunately not.  I have set the JDK version to 11 so all the class files generated by the compiler will not be able to use by Java <11 (that is, 10 and lower).  That was my anxiety...

**Comment by goxr3plus** [comment]
Hm that's not a good idea to break back compatibility.

Can you tell me some good reasons why we should move this project to Java 11 right now :)?

**Comment by goxr3plus** [comment]
Okay look what we will do, have separate releases for Java 8 and Java 11, so let's have a branch named Java 8 and the master branch will be Java 11.

So we will do separate releases for Java 8 and Java 11. Here we go 💓

**Comment by goxr3plus** [comment]
Problem solved.. . easy

**Comment by goxr3plus** [comment]
Hm then we have to go and add the changes on both branches, the feature changes.

**Comment by TonalidadeHidrica** [comment]
The purpose to update JDK version is to use modern features such as module system, local-variable type inference, and possibly, switch expression.  But this breaks backward compatibility you know, and it is able to continue developing without using these features, so updating should not be done - that's my second thought. 
As the purpose of updating JDK version is to use new language feature and make coding easier or more convenient, there's no advantage in separating releases for two JDK versions, I think.

**Comment by TonalidadeHidrica** [comment]
Now the version is 1.8 as before, so you can merge this without worry.

**Comment by goxr3plus** [comment]
WE will soon pass in Java 11, Java 8 will be deprecated... .

What is the difference of the pom.xml in the pull request vs the pom. Xml in the master? It removed completely tritonious share?

If yes, there is a reason tritonious share is there.

Let me know before i merge :)

**Comment by TonalidadeHidrica** [comment]
I completely removed tritonus-share, because all the contents in it are included in tritonus-all, I think.  Or they aren't?  Tell me if there's any problem without tritonus-share.

**Comment by goxr3plus** [comment]
I should open the library and test the files inside.

**Comment by goxr3plus** [comment]
To see if they are the same.

**Comment by TonalidadeHidrica** [comment]
I've confirmed that all the class files in the -share was exactly same to that in -all .  What I did is (sorry,  I used fish shell so it'll not work in bash etc.)
```fish
# unzip -all and -share jars
$ unzip -d all ~/.m2/repository/com/googlecode/soundlibs/tritonus-all/0.3.7.2/tritonus-all-0.3.7.2.jar
$ unzip -d share ~/.m2/repository/com/googlecode/soundlibs/tritonus-share/0.3.7.4/tritonus-share-0.3.7.4.jar

# move to share
$ cd share

# for each class file in current directory, compare with corresponding file in -all
$ for file in (find . | grep 'class$')
      diff $file ../all/$file
  end
# This showed nothing
```

**Comment by goxr3plus** [comment]
Merged :)

**Pull request merged**
