### PR TITLE
Unit tests for gain, new getter for logarithmic gain level.

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
The logarithmic gain getter gets the gain directly from the SourceDataLine. 
We cannot know for sure that it will be logarithmic, but it seems to behave that way.

The pull request is draft, because it changes the interface of the StreamPlayer, by adding a new public method with a name that has not been reviewed.

### CODE REVIEW

**Comment by HelgeStenstrom** [comment]
From my tests, I saw that the gain range on the dB scale was -80 to 6.02 dB. That means that 0 dB is at half of the available linear range. Now these numbers are not visible in the source code, but are properties of the SourceDataLine that I have. It might even be different on Mac and Windows, or depend on the sound card, I don’t know.

Logarithmic dB scale is probably better to work with in an application than a linear scale, for things like control knobs. 

Note that the original gain setting method cannot be called with a linear gain of zero, since that will be converted to minus infinity dB, except that some Exception will be thrown instead.

**Comment by goxr3plus** [comment]
I need to think about it, I don't fully understand the new change yet, you seem professional on this :)

**Comment by HelgeStenstrom** [comment]
https://en.wikipedia.org/wiki/Decibel

**Comment by goxr3plus** [comment]
Thank you i will read

**Comment by HelgeStenstrom** [comment]
I haven't read the Wikipedia article myself, but can say this:
dB (decibel) is generally a measure of power ratios. A power ratio in dB, of P1/P2 = 10 * log10(P1/P2).

Since power is proportional to the square of the amplitude, given two amplitudes V1 and V2, the power ratio can be expressed as 10 * log10( (V1*V1) / (V2*V2) )   = 20 * log10(V1/V2).

A doubled amplitude is approximately 6 dB. 20*log10(2) = 6.02.

In this case, the scale chosen in the implementation of SourceDataLine on my computer is that 0 dB is 6.02 dB below the maximum gain, which means that the linear maximum gain is 2. 

Reading the JavaDoc for SourceDataLine, properties for maximum gain, I see nothing about there bein a logarithmic dB scale. There is apparently no guarantee. On my MacBook, the gain scale is logarithmic, but I cannot know if it is so on other computers.

**Comment by goxr3plus** [comment]
I will merge for now :)

**Pull request merged**
