### PR TITLE
Some unit tests

### PR DESCRIPTION
**Pull request by HelgeStenstrom**
In the TimeTool test, I think I've found a bug. Check lines 45 and 46.

The tests are written to document the current behavior, rather than to guard against bugs.

The time duration test don't test very much. It's because the method needs input data that I can't easily create in the test. With test-driven development, the method would have been written in a different way.

### CODE REVIEW

**Comment by goxr3plus** [comment]
I don't completely understand how is a bug in line 45 and 46 ?

**Comment by HelgeStenstrom** [comment]
What I mean is that 1001 ms returns a result that is less than the result returned by 999 ms. The method behaves like a modulus or remainder function. Is that the intention?

**Comment by HelgeStenstrom** [comment]
To be even more clear:
If 
TimeTool.millisecondsToTime(999) == "0.9"
then I expect 
TimeTool.millisecondsToTime(1001) == "1.0"

but my expectations may be wrong. What are your expectations?

**Comment by goxr3plus** [comment]
Yep, i might have to take a deeper look at it :)

**Comment by goxr3plus** [comment]
I am merging your commits for now, can you open an issue about it so i fix it :)?

**Comment by goxr3plus** [comment]
Ouh can you mergr because i can't? Why actually i can't that's so strange, like i cannot merge some pull requests.

**Comment by HelgeStenstrom** [comment]
This is how it looks for me right now. 
Skärmklipp 2019-09-02 20 48 36
So I can merge, can't you?

**Comment by goxr3plus** [comment]
Now i can :)  Please open an issue about the bug you found.

**Pull request merged**
